apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
data:
  environment: {{ .Values.configMaps.environment | quote }}
  next-public-api-url: {{ .Values.frontend.env.NEXT_PUBLIC_API_URL | quote }}