apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  secret-key: {{ .Values.secrets.secretKey | b64enc | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}